# -*- coding: utf-8 -*-
"""26A_IASC_PF_Fatima_De_la_Paz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WSCqfE0XBjPKvcZFLyFeUenYJWe2yNGM
"""

!pip install ultralytics roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="rF95TeCjKiGuJR8RKyII")
project = rf.workspace("fatimas-workspace-0fd46").project("proyecto-funal_ia")
version = project.version(1)
dataset = version.download("yolov8")

import glob
print("🔍 Tu archivo data.yaml está exactamente en:")
print(glob.glob('/content/**/data.yaml', recursive=True))

import os
os.rename('/content/Proyecto:Funal_IA-1', '/content/Proyecto_Funal_IA')
print("✅ ¡Nombre de la carpeta corregido a: Proyecto_Funal_IA!")

import yaml

yaml_path = '/content/Proyecto_Funal_IA/data.yaml'

# Leer la configuración actual de Roboflow
with open(yaml_path, 'r') as f:
    data = yaml.safe_load(f)

# Corregir las rutas internas para que use la carpeta existente 'train'
data['val'] = '/content/Proyecto_Funal_IA/train/images'
if 'test' in data:
    data['test'] = '/content/Proyecto_Funal_IA/train/images'

# Guardar los cambios en el archivo original
with open(yaml_path, 'w') as f:
    yaml.safe_dump(data, f)

print("✅ ¡Archivo data.yaml adaptado con éxito para tu dataset sin validación externa!")

import os
import random
import numpy as np
import torch
from ultralytics import YOLO

# Fijar semillas para reproducibilidad
random.seed(42)
np.random.seed(42)
torch.manual_seed(42)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(42)

# Configurar el dispositivo en GPU
device = '0' if torch.cuda.is_available() else 'cpu'
print(f"🔥 Entrenando en: {'GPU T4' if device == '0' else 'CPU'}")

# Cargar el modelo base YOLOv8nano
model = YOLO('yolov8n.pt')

if __name__ == '__main__':
    model.train(
        data='/content/Proyecto_Funal_IA/data.yaml', # <--- NUEVA RUTA LIMPIA
        epochs=40,
        imgsz=640,
        device=device,
        patience=10,         # PARO DE EMERGENCIA
        dropout=0.1,         # TÉCNICA DE REGULARIZACIÓN
        val=True,
        deterministic=True,
        seed=42
    )
    print("✅ ¡Entrenamiento completado!")

import pandas as pd
import matplotlib.pyplot as plt
import cv2
from google.colab.patches import cv2_imshow

# 1. Crear gráficas propias desde el archivo csv generado en train-2
try:
    df = pd.read_csv('/content/runs/detect/train-2/results.csv')
    df.columns = df.columns.str.strip()

    plt.figure(figsize=(12, 4))
    plt.subplot(1, 2, 1)
    plt.plot(df['epoch'], df['train/box_loss'], label='Pérdida Entrenamiento', color='blue')
    plt.plot(df['epoch'], df['val/box_loss'], label='Pérdida Validación', color='orange')
    plt.title('Mis Curvas Propias de Pérdida (Box Loss)')
    plt.xlabel('Épocas')
    plt.ylabel('Pérdida')
    plt.legend()
    plt.grid(True)

    plt.subplot(1, 2, 2)
    plt.plot(df['epoch'], df['metrics/mAP50(B)'], color='green', label='mAP50')
    plt.title('Mi Evolución de Precisión Propia (mAP50)')
    plt.xlabel('Épocas')
    plt.ylabel('Precisión')
    plt.legend()
    plt.grid(True)
    plt.show()
except Exception as e:
    print("Error al leer los resultados actuales:", e)

# 2. Mostrar la Matriz de Confusión en tu cuaderno propio
print("\n📈 Mi Matriz de Confusión Personalizada:")
img = cv2.imread('/content/runs/detect/train-2/confusion_matrix.png')
if img is not None:
    cv2_imshow(img)
else:
    print("No se encontró el archivo de la matriz en train-2.")

import shutil
from google.colab import files

# Comprimir la carpeta runs para respaldar todos los archivos generados
shutil.make_archive('/content/26A_IASC_PF_Fatima_De_la_Paz_Runs', 'zip', '/content/runs')

# Descargar automáticamente el archivo comprimido a tu computadora
files.download('/content/26A_IASC_PF_Fatima_De_la_Paz_Runs.zip')
print("\n📂 ¡El archivo comprimido se está descargando en tu computadora!")